'use client'

import { useEffect, useMemo, useState } from 'react'
import { Activity, Check, ChevronDown, ChevronRight, CircleDot, Code2, Folder, LayoutDashboard, Menu, Monitor, Play, RotateCcw, Send, Settings2, ShieldCheck, Sparkles, Upload, Wand2, X, Zap } from 'lucide-react'

type View = 'blueprint' | 'code' | 'sandbox' | 'hub'
const nav = [{ id: 'blueprint', label: 'Blueprint Studio', icon: Wand2 }, { id: 'code', label: 'AI Code Studio', icon: Code2 }, { id: 'sandbox', label: 'Live Sandbox', icon: Monitor }, { id: 'hub', label: 'Providers & Deploy', icon: Settings2 }]
const logs = ['🧠 Thought for 3s', '🔍 Read project repository', '✨ Generated glassmorphic UI layout', '🗄️ Injected Supabase database tables', '✅ Production Live Deploy']
const fileClips: Record<string, string> = { 'app/page.tsx': 'export default function App() { return <main className="rounded-2xl">Build beyond.</main> }', 'components/Builder.tsx': 'export function CompilerWidget() { /* recursive prompt handler */ }', 'styles/globals.css': '@theme { --color-primary: oklch(0.8 0.18 195); }', 'backend/api/generate.ts': 'export async function POST() { return generateText() }' }

export default function Page() {
  const [view, setView] = useState<View>('blueprint'), [menuOpen, setMenuOpen] = useState(false), [stage, setStage] = useState(0), [prompt, setPrompt] = useState('A focused AI workspace for autonomous product teams'), [refs, setRefs] = useState(0), [model, setModel] = useState('VisionBuild-Standard'), [agentLogs, setAgentLogs] = useState<string[]>([]), [credits, setCredits] = useState('Infinite (Developer Tier)'), [activeFile, setActiveFile] = useState('app/page.tsx'), [expanded, setExpanded] = useState<string[]>([]), [code, setCode] = useState(fileClips['app/page.tsx']), [logTab, setLogTab] = useState('Terminal'), [codeTab, setCodeTab] = useState('Editor'), [sandboxMode, setSandboxMode] = useState('mobile'), [vaultOpen, setVaultOpen] = useState(false)
  const [vault, setVault] = useState({ supabase: '', bucket: '', openai: '' })
  const blueprint = useMemo(() => ({ name: prompt.split(' ').slice(0, 3).join(' ') || 'Vision Workspace', pages: ['Command Center', 'Project Archive', 'Live Sandbox'], features: ['Prompt-to-app compiler', 'Screen review workflow', 'Deployment snapshots'], schema: ['projects', 'project_versions', 'assets'] }), [prompt])
  useEffect(() => { try { const saved = sessionStorage.getItem('visionbuild-model'); if (saved) setModel(saved) } catch {} }, [])
  useEffect(() => { try { sessionStorage.setItem('visionbuild-model', model) } catch {} }, [model])
  async function compileApplication() { setAgentLogs([]); setView('code'); try { const response = await fetch('/api/generate', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ prompt }) }); if (!response.ok || !response.body) { setAgentLogs(['Agent error · unable to start autonomous build']); return } const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ''; while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const lines = buffer.split('\n'); buffer = lines.pop() || ''; for (const line of lines) { if (!line) continue; try { const event = JSON.parse(line) as { type: string; message?: string; path?: string; content?: string }; if (event.message) setAgentLogs(current => [...current, event.message as string]); if (event.path && event.content) { setActiveFile(event.path); setCode(event.content) } } catch {} } } } catch { setAgentLogs(current => [...current, 'Agent error · connection interrupted']) } }
  function resetExecution() { setAgentLogs([]); setCredits('Infinite (Developer Tier)') }
  function selectFile(file: string) { setActiveFile(file); setCode(fileClips[file] || '// Empty source clip') }
  return <main className={`vb-app model-${model === 'VisionBuild-Max' ? 'max' : 'standard'}`}><header className="topbar"><button className="brand" onClick={() => setView('blueprint')}><span className="brand-mark"><Sparkles /></span><span><strong>VISIONBUILD</strong><small>AI WORKSPACE</small></span></button><div className="top-status"><span className="live-dot" /> SYSTEM NOMINAL <span className="version">v2.7.0</span><span className="credits-status">Credits Remaining: {credits}</span><button className="reset-loop" onClick={resetExecution} aria-label="Reset execution loop"><RotateCcw /></button></div><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation"><Menu /></button></header><div className={`workspace-shell ${menuOpen ? 'menu-visible' : ''}`}><aside className="sidebar"><div className="sidebar-label">BUILD PIPELINE</div>{nav.map(item => { const Icon = item.icon; return <button key={item.id} className={`nav-item ${view === item.id ? 'active' : ''}`} onClick={() => { setView(item.id as View); setMenuOpen(false) }}><Icon /><span>{item.label}</span>{view === item.id && <ChevronRight className="nav-chevron" />}</button> })}<button className="vault-link" onClick={() => setVaultOpen(true)}><ShieldCheck /> Developer Vault</button></aside><section className="content"><div className="content-header"><div><div className="eyebrow">PHASE 0{nav.findIndex(n => n.id === view) + 1}</div><h1>{nav.find(n => n.id === view)?.label}</h1></div><div className="header-actions"><label className="model-select"><span>NODE</span><select value={model} onChange={e => setModel(e.target.value)}><option>VisionBuild-Standard</option><option>VisionBuild-Max</option></select></label></div></div>{view === 'blueprint' && <Blueprint stage={stage} setStage={setStage} prompt={prompt} setPrompt={setPrompt} refs={refs} setRefs={setRefs} blueprint={blueprint} onBuild={compileApplication} />}{view === 'code' && <CodeStudio code={code} setCode={setCode} activeFile={activeFile} expanded={expanded} setExpanded={setExpanded} selectFile={selectFile} agentLogs={agentLogs} logTab={logTab} setLogTab={setLogTab} codeTab={codeTab} setCodeTab={setCodeTab} />}{view === 'sandbox' && <Sandbox mode={sandboxMode} setMode={setSandboxMode} />}{view === 'hub' && <Hub />}</section></div>{vaultOpen && <div className="vault-modal"><section className="panel"><div className="panel-head"><div><div className="eyebrow">LOCAL HARDWARE CACHE</div><h2>Developer Vault</h2></div><button className="icon-button" onClick={() => setVaultOpen(false)}><X /></button></div>{(['supabase','bucket','openai'] as const).map(key => <label className="field-label" key={key}>{key.toUpperCase()} KEY<input type="password" value={vault[key]} onChange={e => setVault({ ...vault, [key]: e.target.value })} /></label>)}<button className="primary-button" onClick={() => setVaultOpen(false)}>Save locally</button></section></div>}</main>
}

function Blueprint({ stage, setStage, prompt, setPrompt, refs, setRefs, blueprint, onBuild }: any) { return <div className="view-stack"><div className="stage-strip">{['Prompt','References','Detect & target','Blueprint review'].map((x, i) => <button key={x} className={stage === i ? 'stage-active' : ''} onClick={() => setStage(i)}><span>{i + 1}</span>{x}</button>)}</div><section className="panel pipeline-panel"><div className="panel-head"><div><div className="eyebrow">INPUT ORCHESTRATOR</div><h2>Design the next build</h2></div><Zap /></div>{stage === 0 && <><label className="field-label">NATURAL-LANGUAGE BRIEF<textarea value={prompt} onChange={e => setPrompt(e.target.value)} rows={5} /></label><button className="primary-button" onClick={() => setStage(1)}>Continue pipeline <ChevronRight /></button></>}{stage === 1 && <div className="upload-grid">{[0,1,2,3].map(i => <button key={i} className="upload-tile" onClick={() => setRefs(Math.min(4, refs + 1))}>{i < refs ? <><Check /><strong>Reference {i + 1}</strong></> : <><Upload /><strong>Add reference</strong><small>JPG, PNG</small></>}</button>)}</div>}{stage === 2 && <div className="selector-grid"><label className="field-label">APP TYPE<select><option>Mobile dashboard</option><option>Marketing site</option></select></label><label className="field-label">PLATFORM<select><option>Next.js / PWA</option><option>React Native</option></select></label></div>}{stage === 3 && <><div className="blueprint-card"><h2>{blueprint.name}</h2>{Object.entries(blueprint).slice(1).map(([key, value]) => <div className="blueprint-block" key={key}><span>{key}</span><strong>{(value as string[]).join(' · ')}</strong></div>)}</div><button className="primary-button" onClick={onBuild}><Play /> Approve design & compile application</button></>}</section></div> }

function CodeStudio({ code, setCode, activeFile, expanded, setExpanded, selectFile, agentLogs, logTab, setLogTab, codeTab, setCodeTab }: any) { const folders = ['assets','components','backend/api','styles','database']; return <div className="view-stack"><div className="ide-grid"><aside className="panel file-tree"><div className="eyebrow">EXPLORER</div>{folders.map(folder => <div key={folder}><button className="tree-folder" onClick={() => setExpanded((x: string[]) => x.includes(folder) ? x.filter(y => y !== folder) : [...x, folder])}><ChevronDown /><Folder /><strong>/{folder}</strong></button>{expanded.includes(folder) && ['index.tsx','layout.tsx','config.ts'].map(file => <button className="file-node" key={`${folder}/${file}`} onClick={() => selectFile(`${folder}/${file}`)}><Code2 />{file}</button>)}</div>)}</aside><section className="panel editor"><div className="editor-tabs">{['Editor','Assistant'].map(x => <button key={x} className={codeTab === x ? 'tab-active' : ''} onClick={() => setCodeTab(x)}>{x}</button>)}<span className="editor-status"><CircleDot /> {activeFile}</span></div>{codeTab === 'Editor' ? <textarea className="code-editor" value={code} onChange={e => setCode(e.target.value)} spellCheck={false} /> : <div className="assistant"><Sparkles /> AI Coding Assistant<div className="assistant-input"><input placeholder="Describe a code change" /><button className="icon-button"><Send /></button></div></div>}</section></div><section className="panel logs-panel"><div className="log-tabs">{['Terminal','Problems','Build logs','Console'].map(x => <button key={x} className={logTab === x ? 'tab-active' : ''} onClick={() => setLogTab(x)}>{x}</button>)}</div><div className="log-content">{logTab === 'Terminal' ? (agentLogs.length ? agentLogs.map((x: string, i: number) => <div className="agent-log-line" key={`${x}-${i}`}>{x}</div>) : '$ awaiting compile command') : logTab === 'Problems' ? 'No blocking problems detected' : logTab === 'Build logs' ? 'Build graph resolved · artifact ready' : 'Console telemetry connected'}</div></section></div> }
function Sandbox({ mode, setMode }: any) { return <div className="view-stack"><div className="sandbox-toolbar"><h2>Interactive preview</h2><div className="segmented"><button className={mode === 'mobile' ? 'selected' : ''} onClick={() => setMode('mobile')}><Monitor /> Mobile</button><button className={mode === 'desktop' ? 'selected' : ''} onClick={() => setMode('desktop')}><LayoutDashboard /> Desktop</button></div></div><section className={`panel render-frame ${mode}`}><div className="render-app"><div className="render-nav"><Sparkles /> VISIONBUILD <CircleDot /></div><div className="render-hero"><span className="status-chip">LIVE RENDER</span><h3>Build beyond<br /><em>the possible.</em></h3><p>Autonomous product workspace ready.</p></div></div></section></div> }
function Hub() { return <div className="view-stack"><section className="panel providers"><div className="eyebrow">MODEL ROUTING</div><h2>AI provider modules</h2>{['Text AI','Image AI','Image analysis','Code generation','Code analysis','Testing','Custom / self-hosted'].map(x => <div className="provider-row" key={x}><strong>{x}</strong><span className="toggle on"><span /></span></div>)}</section></div> }
