import { createClient } from '@/lib/supabase/server'

function crc32(bytes: Uint8Array) {
  let crc = 0xffffffff
  for (const byte of bytes) { crc ^= byte; for (let i = 0; i < 8; i++) crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0) }
  return (crc ^ 0xffffffff) >>> 0
}
function u16(value: number) { return new Uint8Array([value & 255, (value >>> 8) & 255]) }
function u32(value: number) { return new Uint8Array([value & 255, (value >>> 8) & 255, (value >>> 16) & 255, (value >>> 24) & 255]) }
function zipStore(files: Array<{ name: string; content: string }>) {
  const encoder = new TextEncoder(); const chunks: Uint8Array[] = []; const central: Uint8Array[] = []; let offset = 0
  for (const file of files) { const name = encoder.encode(file.name); const data = encoder.encode(file.content); const header = new Uint8Array(30 + name.length); header.set([80,75,3,4], 0); header.set(u16(20), 4); header.set(u16(0), 6); header.set(u16(0), 8); header.set(u16(0), 10); header.set(u16(0), 12); header.set(u32(crc32(data)), 14); header.set(u32(data.length), 18); header.set(u32(data.length), 22); header.set(u16(name.length), 26); header.set(u16(0), 28); header.set(name, 30); chunks.push(header, data); const entry = new Uint8Array(46 + name.length); entry.set([80,75,1,2], 0); entry.set(u16(20), 4); entry.set(u16(20), 6); entry.set(u16(0), 8); entry.set(u16(0), 10); entry.set(u16(0), 12); entry.set(u16(0), 14); entry.set(u32(crc32(data)), 16); entry.set(u32(data.length), 20); entry.set(u32(data.length), 24); entry.set(u16(name.length), 28); entry.set(u16(0), 30); entry.set(u16(0), 32); entry.set(u16(0), 34); entry.set(u16(0), 36); entry.set(u32(0), 38); entry.set(u32(offset), 42); entry.set(name, 46); central.push(entry); offset += header.length + data.length }
  const centralSize = central.reduce((sum, item) => sum + item.length, 0); const end = new Uint8Array(22); end.set([80,75,5,6], 0); end.set(u16(files.length), 8); end.set(u16(files.length), 10); end.set(u32(centralSize), 12); end.set(u32(offset), 16); const output = new Uint8Array(offset + centralSize + 22); let cursor = 0; for (const chunk of [...chunks, ...central, end]) { output.set(chunk, cursor); cursor += chunk.length } return output
}

export async function POST(request: Request) {
  const supabase = await createClient(); const body = await request.json().catch(() => ({})) as { projectId?: string; code?: string }
  let code = body.code?.trim() || ''
  if (body.projectId) { const { data } = await supabase.from('projects').select('generated_code').eq('id', body.projectId).maybeSingle(); code ||= data?.generated_code || '' }
  if (!code) return Response.json({ error: 'No generated project is available to export.' }, { status: 400 })
  const zip = zipStore([{ name: 'app/GeneratedApp.tsx', content: code }, { name: 'README.txt', content: 'Generated by VisionBuild AI.\n' }])
  return new Response(zip, { headers: { 'content-type': 'application/zip', 'content-disposition': 'attachment; filename="visionbuild-project.zip"', 'content-length': String(zip.byteLength) } })
}
